package xyz.yhsj.music.utils

/**
 * 音乐action
 */
object BroadcastAction {
    /*操作指令*/
    val ACTION_OPT_MUSIC_PLAY = "ACTION_OPT_MUSIC_PLAY"
    val ACTION_OPT_MUSIC_PAUSE = "ACTION_OPT_MUSIC_PAUSE"
    val ACTION_OPT_MUSIC_NEXT = "ACTION_OPT_MUSIC_NEXT"
    val ACTION_OPT_MUSIC_LAST = "ACTION_OPT_MUSIC_LAST"
    val ACTION_OPT_MUSIC_SEEK_TO = "ACTION_OPT_MUSIC_SEEK_TO"

    /*状态指令*/
    val ACTION_STATUS_MUSIC_PLAY = "ACTION_STATUS_MUSIC_PLAY"
    val ACTION_STATUS_MUSIC_PAUSE = "ACTION_STATUS_MUSIC_PAUSE"
    val ACTION_STATUS_MUSIC_COMPLETE = "ACTION_STATUS_MUSIC_COMPLETE"
    val ACTION_STATUS_MUSIC_DURATION = "ACTION_STATUS_MUSIC_DURATION"

    val PARAM_MUSIC_DURATION = "PARAM_MUSIC_DURATION"
    val PARAM_MUSIC_SEEK_TO = "PARAM_MUSIC_SEEK_TO"
    val PARAM_MUSIC_CURRENT_POSITION = "PARAM_MUSIC_CURRENT_POSITION"
    val PARAM_MUSIC_IS_OVER = "PARAM_MUSIC_IS_OVER"
}